[package]
name = "vmmapi"
version = "0.1.0"
description = "Crate providing an ffi wrapper around the illumos bhyve vmmapi"
authors = ["Mike Zeller <mike@mikezeller.net>"]
edition = "2018"

[dependencies]
